### ISSUE TITLE
Create an open member list

### ISSUE THREAD

**Issue by moul** [atomone-hub/genesis#30]
Before anyone can fully align with the constitution as a member, I believe it's important to establish a temporary space for individuals to express their interest in contributing to the project. This allows them to participate in its development without the obligation of committing to the final decisions.

For this purpose, we could create a list that serves as the basis for a mailing list. This list would be used to organize Google Meet sessions where open discussions can take place, helping to minimize scams compared to a completely open system.

I propose setting up a dedicated repository in the Atomone-hub organization. Here, interested individuals can either create an issue or a pull request to add a file with their details, like so:

```yaml
name: Manfred Touron
github_handle: @moul  
email: manfred@tendermint.com
intro: “Blockchain engineer, decentralization enthusiast”
```

Intro could be: “Curious stalker” (not limited to builders).

Additionally, it would be beneficial to implement a mechanism to prevent email spam, while still allowing us to compile a list of email addresses for meeting invitations. This could be a simple cryptographic solution or perhaps a Google Form.

However, I think it's crucial that we maintain transparency and public engagement in this process.
